using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectExchange.Core.Migrations
{
    /// <inheritdoc />
    public partial class AddDomainEventsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE public.domain_events (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_type character varying(64) NOT NULL,
                    payload jsonb NOT NULL,
                    occurred_at timestamp with time zone NOT NULL,
                    market_id character varying(128) NULL,
                    user_id character varying(128) NULL
                );");

            migrationBuilder.CreateIndex(
                name: "ix_domain_events_market_id",
                schema: "public",
                table: "domain_events",
                column: "market_id");

            migrationBuilder.CreateIndex(
                name: "ix_domain_events_occurred_at",
                schema: "public",
                table: "domain_events",
                column: "occurred_at");

            migrationBuilder.CreateIndex(
                name: "ix_domain_events_user_id",
                schema: "public",
                table: "domain_events",
                column: "user_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "domain_events",
                schema: "public");
        }
    }
}
