// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectExchange.Core.Infrastructure.Persistence;

#nullable disable

namespace ProjectExchange.Core.Migrations
{
    [DbContext(typeof(ProjectExchangeDbContext))]
    [Migration("20260203233013_InitialSnakeCase")]
    partial class InitialSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("OperatorId", "Name")
                        .HasDatabaseName("ix_accounts_operator_id_name");

                    b.ToTable("accounts", "public");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.JournalEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer")
                        .HasColumnName("entry_type");

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_entries_account_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_journal_entries_transaction_id");

                    b.ToTable("journal_entries", "public");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.LedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_type");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_ledger_entries_timestamp");

                    b.ToTable("ledger_entries", "public");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OutcomeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("outcome_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "public");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("SettlesClearingTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("settles_clearing_transaction_id");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.ToTable("transactions", "public");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.JournalEntryEntity", b =>
                {
                    b.HasOne("ProjectExchange.Core.Infrastructure.Persistence.TransactionEntity", "Transaction")
                        .WithMany("JournalEntries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.TransactionEntity", b =>
                {
                    b.Navigation("JournalEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
