// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectExchange.Core.Infrastructure.Persistence;

#nullable disable

namespace ProjectExchange.Core.Migrations
{
    [DbContext(typeof(ProjectExchangeDbContext))]
    [Migration("20260207000000_AddFollowersTable")]
    partial class AddFollowersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectExchange.Core.Infrastructure.Persistence.FollowerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("follower_id");

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("leader_id");

                    b.HasKey("Id")
                        .HasName("pk_followers");

                    b.HasIndex("FollowerId", "LeaderId")
                        .IsUnique()
                        .HasDatabaseName("ix_followers_follower_id_leader_id");

                    b.HasIndex("LeaderId")
                        .HasDatabaseName("ix_followers_leader_id");

                    b.ToTable("followers", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
