using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectExchange.Core.Migrations
{
    /// <inheritdoc />
    public partial class AddFollowersTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE public.followers (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    follower_id character varying(128) NOT NULL,
                    leader_id character varying(128) NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
                );
                CREATE UNIQUE INDEX ix_followers_follower_id_leader_id ON public.followers (follower_id, leader_id);
                CREATE INDEX ix_followers_leader_id ON public.followers (leader_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "followers",
                schema: "public");
        }
    }
}
